import Counter from "@/components/Counter";
import Descriptions from "@/components/Descriptions";
import Dog from "@/components/Dog";
import Form from "@/components/Form";
import Parent from "@/components/Parent";
import TaskList from "@/components/TaskList";
import TrafficLight from "@/components/TrafficLight";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {

  return (
    <>
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello world!</h1>
        {/* Comentário em JSX */}
        {/* Chamando o componente */}
        <Welcome />
        {/* Importando o componente User que possui uma expressão JSX */}
        <User />
        {/* Componente pai que possui um compnente filho incorporado */}
        <Parent />
        {/* Chamando o componente e passando as props para o mesmo: */}
        <Descriptions name="Diego" age={18} />
        {/* Usando a desestruturação para passar props */}
        <Dog name="Rex" breed="Pitbull" />
        {/* Contador */}
        <Counter />
        {/* Semáforo {Estados} */}
        <TrafficLight />
        {/* Formulário */}
        <br />
        <Form />
        <br />
        {/* TaskList */}
        <TaskList  tasks={[
          {
            id:1,
            descricao: "1. Estudar React"
          },
          {
            id:2,
            descricao: "2. Estudar Java"
          },
          {
            id:3,
            descricao: "3. Estudar Js"
          },
          {
            id:4,
            descricao: "4. Estudar Python"
          }
          ]}  
          /*tasks = {[]}
          */
          />
      </main>
    </>
  );
}
